#!/bin/bash

#sed "s@{{TITLE}}@${TITLE:-Etherpad}@g" -i /etherpad-lite/settings.json
#sed "s@{{DB_HOST}}@${POSTGRESQL_PORT_5432_TCP_ADDR}@g" -i /etherpad-lite/settings.json
#sed "s@{{DEFAULT_PAD_TEXT}}@$${DEFAULT_PAD_TEXT:-}@g" -i /etherpad-lite/settings.json
#sed "s@{{ADMIN_PW}}@${ADMIN_PW:-password}@g" -i /etherpad-lite/settings.json
#sed "s@{{DB_NAME}}@${DB_NAME:-pad}@g" -i /etherpad-lite/settings.json
#sed "s@{{DB_USER}}@${DB_USER:-postgres}@g" -i /etherpad-lite/settings.json
#sed "s@{{DB_PASSWORD}}@${DB_PASSWORD:-pad}@g" -i /etherpad-lite/settings.json
